// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfYcGEbWZw1awtkSWuJV__cPmwAyyh0Wg',
    appId: '1:748023398536:web:efc45f6e35e2ac3e2bdf3d',
    messagingSenderId: '748023398536',
    projectId: 'sushi-box-d7a35',
    authDomain: 'sushi-box-d7a35.firebaseapp.com',
    storageBucket: 'sushi-box-d7a35.appspot.com',
    measurementId: 'G-6KHTS1X9EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEffL9Yh5T-r7tGxbzp4mqt3l8HcQ0n0A',
    appId: '1:748023398536:android:52c7db71f0421ba62bdf3d',
    messagingSenderId: '748023398536',
    projectId: 'sushi-box-d7a35',
    storageBucket: 'sushi-box-d7a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHr7zRQxMRhcLgA7q4RDXxKm-TnTwYvE',
    appId: '1:748023398536:ios:0b11e9936138f2d42bdf3d',
    messagingSenderId: '748023398536',
    projectId: 'sushi-box-d7a35',
    storageBucket: 'sushi-box-d7a35.appspot.com',
    iosBundleId: 'com.example.sushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqHr7zRQxMRhcLgA7q4RDXxKm-TnTwYvE',
    appId: '1:748023398536:ios:0b11e9936138f2d42bdf3d',
    messagingSenderId: '748023398536',
    projectId: 'sushi-box-d7a35',
    storageBucket: 'sushi-box-d7a35.appspot.com',
    iosBundleId: 'com.example.sushi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfYcGEbWZw1awtkSWuJV__cPmwAyyh0Wg',
    appId: '1:748023398536:web:26c19ee1a34af2522bdf3d',
    messagingSenderId: '748023398536',
    projectId: 'sushi-box-d7a35',
    authDomain: 'sushi-box-d7a35.firebaseapp.com',
    storageBucket: 'sushi-box-d7a35.appspot.com',
    measurementId: 'G-Y419L07NZZ',
  );
}
